import turtle as t

# Scale factor
scale = 0.7

# Initialize settings
t.pensize(3 * scale)
t.speed(99)

# Draw head
t.penup()
t.goto(-200 * scale, 180 * scale)
t.pendown()
t.fillcolor("yellow")
t.begin_fill()
t.seth(-30)
for _ in range(6):
    t.circle(36 * scale, 60)
    t.circle(-36 * scale, 60)
t.seth(-125)
for _ in range(5):
    t.circle(40 * scale, 60)
    t.circle(-40 * scale, 60)
t.seth(-210)
for _ in range(4):
    t.circle(45 * scale, 60)
    t.circle(-45 * scale, 60)
t.seth(65)
for _ in range(5):
    t.circle(40 * scale, 60)
    t.circle(-40 * scale, 60)
t.end_fill()

t.penup()
t.goto(-110 * scale, 130 * scale)
t.pendown()
t.fillcolor('#e9d700')
t.begin_fill()
t.circle(9)
t.end_fill()

t.penup()
t.goto(-110 * scale, -130 * scale)
t.pendown()
t.fillcolor('#e9d700')
t.begin_fill()
t.circle(15)
t.end_fill()


t.penup()
t.goto(170 * scale, 100 * scale)
t.pendown()
t.fillcolor('#e9d700')
t.begin_fill()
t.circle(21)
t.end_fill()


t.penup()
t.goto(185 * scale, -160 * scale)
t.pendown()
t.fillcolor('#e9d700')
t.begin_fill()
t.circle(17)
t.end_fill()


# Draw eye
t.penup()
t.goto(14 * scale, -5 * scale)
t.pendown()
t.fillcolor('#f0f0f0')
t.begin_fill()
t.circle(65 * scale, 360)
t.end_fill()
t.begin_fill()
t.penup()
t.goto(13 * scale, 12 * scale)
t.pendown()
t.seth(98)
t.circle(-65 * scale, 360)
t.end_fill()

# Draw eyeball
t.penup()
t.goto(-10 * scale, 20 * scale)
t.pendown()
t.fillcolor('blue')
t.begin_fill()
t.circle(20 * scale, 360)
t.end_fill()
t.penup()
t.goto(-22 * scale, 20 * scale)
t.pendown()
t.fillcolor('black')
t.begin_fill()
t.circle(7 * scale, 360)
t.end_fill()
t.penup()
t.goto(40 * scale, 15 * scale)
t.pendown()
t.fillcolor('blue')
t.begin_fill()
t.circle(-20 * scale, 360)
t.end_fill()
t.penup()
t.goto(53 * scale, 15 * scale)
t.pendown()
t.fillcolor('black')
t.begin_fill()
t.circle(-7 * scale, 360)
t.end_fill()

# Draw eyelashes
t.penup()
t.goto(-95 * scale, 65 * scale)
t.pendown()
t.left(20)
t.forward(40 * scale)
t.penup()
t.goto(-50 * scale, 87 * scale)
t.pendown()
t.right(25)
t.forward(32 * scale)
t.penup()
t.goto(0, 70 * scale)
t.pendown()
t.right(25)
t.forward(40 * scale)

t.penup()
t.goto(40 * scale, 75 * scale)
t.pendown()
t.left(35)
t.forward(40 * scale)
t.penup()
t.goto(90 * scale, 87 * scale)
t.pendown()
t.right(18)
t.forward(30 * scale)
t.penup()
t.goto(120 * scale, 70 * scale)
t.pendown()
t.right(25)
t.forward(40 * scale)

# Draw nose
t.fillcolor('yellow')
t.penup()
t.goto(0, -7 * scale)
t.pendown()
t.begin_fill()
t.right(50)
t.circle(-60 * scale, 30)
t.color('yellow')
t.goto(15 * scale, -40 * scale)
t.end_fill()
t.color('black')
t.penup()
t.goto(0, -7 * scale)
t.pendown()
t.seth(-75)
t.forward(30 * scale)
t.penup()
t.goto(30 * scale, -7 * scale)
t.pendown()
t.seth(-105)
t.forward(30 * scale)

# Draw mouth
t.penup()
t.goto(-120 * scale, -60 * scale)
t.pendown()
t.seth(-45)
t.circle(200 * scale, 30)
t.seth(0)
t.forward(100 * scale)
t.seth(15)
t.circle(200 * scale, 30)

# Draw teeth
t.penup()
t.goto(-30 * scale, -114 * scale)
t.pendown()
t.seth(-95)
t.fillcolor('white')
t.begin_fill()
t.forward(30 * scale)
t.seth(0)
t.forward(40 * scale)
t.seth(95)
t.forward(30 * scale)
t.penup()
t.goto(-30 * scale, -114 * scale)
t.pendown()
t.end_fill()

t.penup()
t.goto(30 * scale, -114 * scale)
t.pendown()
t.seth(-95)
t.fillcolor('white')
t.begin_fill()
t.forward(30 * scale)
t.seth(0)
t.forward(40 * scale)
t.seth(95)
t.forward(30 * scale)
t.penup()
t.goto(60 * scale, -114 * scale)
t.pendown()
t.end_fill()

# Draw body
t.penup()
t.goto(-170 * scale, -180 * scale)
t.pendown()
t.seth(-120)
t.circle(150 * scale, 30)
t.seth(0)
t.forward(40 * scale)
t.seth(100)
t.forward(35 * scale)
t.seth(-80)
t.forward(100 * scale)
t.fillcolor('brown')
t.begin_fill()
t.seth(0)
t.forward(300 * scale)
t.seth(80)
t.forward(110 * scale)
t.seth(-100)
t.forward(65 * scale)
t.seth(180)
t.forward(315 * scale)
t.end_fill()
t.penup()
t.goto(-118 * scale, -400 * scale)
t.goto(-170 * scale, -255 * scale)
t.pendown()
t.fillcolor('yellow')
t.begin_fill()
t.seth(-75)
t.forward(80 * scale)
t.seth(0)
t.forward(17 * scale)
t.seth(105)
t.forward(85 * scale)
t.end_fill()

t.penup()
t.goto(200 * scale, -170 * scale)
t.pendown()
t.seth(-60)
t.circle(-150 * scale, 30)
t.seth(-180)
t.forward(45 * scale)
t.begin_fill()
t.seth(0)
t.forward(20 * scale)
t.seth(-100)
t.forward(85 * scale)
t.seth(180)
t.forward(20 * scale)
t.end_fill()

# Draw tie
t.penup()
t.goto(-50 * scale, -225 * scale)
t.pendown()
t.seth(-40)
t.forward(40 * scale)
t.seth(30)
t.forward(52 * scale)
t.penup()
t.goto(30 * scale, -225 * scale)
t.pendown()
t.seth(-30)
t.forward(40 * scale)
t.seth(40)
t.forward(45 * scale)
t.fillcolor('red')
t.penup()
t.goto(0, -240 * scale)
t.pendown()
t.begin_fill()
t.seth(-60)
t.forward(10 * scale)
t.seth(0)
t.forward(30 * scale)
t.seth(60)
t.forward(15 * scale)
t.penup()
t.goto(30 * scale, -225 * scale)
t.pendown()
t.end_fill()
t.penup()
t.goto(4 * scale, -250 * scale)
t.pendown()
t.begin_fill()
t.seth(-100)
t.forward(80 * scale)
t.seth(0)
t.forward(55 * scale)
t.seth(100)
t.forward(80 * scale)
t.end_fill()

# Draw legs
t.penup()
t.goto(-100 * scale, -320 * scale)
t.pendown()
t.fillcolor('yellow')
t.begin_fill()
t.seth(-90)
t.forward(80 * scale)
t.seth(0)
t.forward(25 * scale)
t.seth(90)
t.forward(80 * scale)
t.end_fill()

t.penup()
t.goto(100 * scale, -320 * scale)
t.pendown()
t.begin_fill()
t.seth(-90)
t.forward(80 * scale)
t.seth(0)
t.forward(25 * scale)
t.seth(90)
t.forward(80 * scale)
t.end_fill()


#Finish
t.pensize(2)
t.penup()
t.goto(0, 0)
t.goto(-100 * scale, 240 * scale)
t.hideturtle()
t.done()
